repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-toml
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: requirements-txt-fixer

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.2
  hooks:
  - id: markdownlint-fix

- repo: https://github.com/dannysepler/rm_unneeded_f_str
  rev: v0.1.0
  hooks:
  - id: rm-unneeded-f-str

- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
    - id: absolufy-imports

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort

- repo: https://github.com/python/black
  rev: 22.3.0
  hooks:
    - id: black

- repo: https://github.com/fsouza/autoflake8
  rev: v0.2.2
  hooks:
    - id: autoflake8
      args: ['--recursive', '--in-place']

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8

- repo: https://github.com/jendrikseipp/vulture
  rev: v2.3
  hooks:
    - id: vulture
